language: node_js
node_js:
- '8.10'
deploy:
  provider: npm
  email: Matt.Lloyd101@gmail.com
  api_key:
    secure: P81UuypXBK0Lv0+o9c5dUE2kTKR59Dv4H0y6JRhrXYs6M2EPLccl2PdjXMB2kmDN9v8ZNUhK6UY5QR5z8374lH838dN46jTnSAr9prRXk1udD3DrjPs11/YcDGu2peySHBqu/maqUjWndUtt27ijeB1E0w9ATSEIODqK4Y5fn7LQM59uba0ZcZpqGKFzoy85dG82mzjQdm9mvHmuhLwYBORyEbTpwPFlnjGaTN22ec42EHB5SX4Umla/O8kjqbSMczyetcPjRY4mi1o2n4/9gEUuGvisvMDlSdxjwxg+eejlBVmJUT44DP/nXv2nprk6dI45ZcB/m24HB82yvEV6KS8Z0kWeiP2rsshwnlMCua7+JLpgERlY4KnoBGPfogtTgFODEc4bArTUVYLcbph6lCxLxwvn8Fk3OztzXShPsEs1sJoDfG15T1JLgCQXupe8+ewInbDvuzpTLSwitMg+XVSPmcB36XFaRPqZJ8x5hN+CHpmjw5BrQ71Z7p6XAwLR91DVbuoMib6Y71/UriUmT8S46ijM5AsPr9j1sEoB1iTAYkca8H2Xsm9PChENCNeyJctXbxuWy09EzyQ9PLne79GLsnwrWSDpX985rRwPFpRje9TjlDU29oqbYTEjmcq2hzqU41tFvL2+iYLzLCuM5Ef+fUQXiXeNkOZfFzP4wkk=
  on:
    tags: true
    repo: MattLloyd101/Hoodwinker
